Fix tests
viasite-ansible/ansible-role-kapacitor pull request #1
Opened 2017-07-06 12:55 UTC by mplachter

# Changes for Branch
---------------------
* Restructured project to make idempotence
  * Broke up condition tasks to handlers
  * Made Configure Ticks File
* Fixed tests
  * Added Travis File
     * Removed gitlab ci
  * Added More Tests
* Passing Travis Build
  * https://github.com/mplachter/ansible-role-kapacitor
    * Created new branch so travis badge would be from current repo CI

No installation/configuration changes were made. 
This was just to get the CI working.

2017-07-11 19:08 UTC, popstas requested changes
Thank you, found some new ansible features and use cases of molecule from your PR ) Leaved some comments at code, please check. 

Only one request: please don't delete `.gitlab-ci.yml`.

I hope that I will test it tomorrow on real machine, then PR will be merged.

2017-07-11 19:08 UTC, popstas commented on .gitlab-ci.yml
> ----
I need gitlab-ci for vagrant full test

2017-07-11 19:08 UTC, popstas commented on .travis.yml
> +  - pip install ansible
Molecule installs ansible as dependency, not necessary to install it explicitly

2017-07-11 19:08 UTC, popstas commented on tasks/configure-thresholds.yml
> +    force: yes
Why force?

2017-07-12 01:29 UTC, mplachter commented on .travis.yml
> +  - pip install ansible
I agree, this is redundant.

2017-07-12 01:29 UTC, mplachter commented on tasks/configure-thresholds.yml
> +    force: yes
Force is default yes this is redundant.

2017-07-12 01:30 UTC, mplachter commented on .gitlab-ci.yml
> ----
Sorry about that, i will add back the gitlab-ci.

2017-07-13 10:52 UTC, popstas approved these changes

2017-07-13 10:56 UTC, popstas commented
Good! What about squash commits from 20+ to 1-5? I ready to merge as is, but I think, that your commits kind of... verbose. What you think about it?

2017-07-13 18:19 UTC, mplachter commented
Yeah i can squash them 👍

2017-07-14 05:24 UTC, merged

2017-07-14 05:25 UTC, popstas commented
Good job, thank you!